SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_C_COMPILER   i586-mingw32msvc-gcc)

SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wall")
SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Wall -DNDEBUG")

